### ISSUE TITLE
Cech optimizations

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#646]
So we don't forget, optimization ideas for Cech construction:
- [ ] #642
- [ ] https://github.com/GUDHI/gudhi-devel/pull/519#discussion_r901006801
- [ ] https://github.com/GUDHI/gudhi-devel/pull/519#discussion_r901007021

**Comment by Hind-M** [comment]
This issue can be closed:
* [x]  [[Cech] Get extra point using boundary_opposite_vertex_simplex_range #642](https://github.com/GUDHI/gudhi-devel/pull/642)
Merged.
* [x]  [Cech optimization #519 (comment)](https://github.com/GUDHI/gudhi-devel/pull/519#discussion_r901006801)
cf. #650 
* [x]  [Cech optimization #519 (comment)](https://github.com/GUDHI/gudhi-devel/pull/519#discussion_r901007021)
cf. #652

**Comment by VincentRouvreau** [comment]
The 3 different points are merged so I close this issue
